language: node_js
node_js:
  - "node"
services: mongodb
addons:
  hosts:
    - mongodb
  packages:
    - g++-5
before_script:
  - cp ${TRAVIS_BUILD_DIR}/config/default.template.json ${TRAVIS_BUILD_DIR}/config/default.json
script:
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
